---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r}
library(dplyr)
library(tidyr)
library(tree)
library(captchatjsp)
library(caret)
```

### Mostrando

```{r}
d <- ler(baixar())
desenhar(d)

# path <- 'inst/treino/'
# classificar(picotar(limpar(d)), 'qmiqx', path)
```

### Atualizar modelo

#### Base de treino
```{r}
set.seed(123)
d_min <- carregar_treino('C:/Users/Athos/Downloads/treino/minusculo/')
d_min$letra <- as.factor(d_min$letra)
linhas_treino <- sample(nrow(d_min), 0.8*nrow(d_min))
d_treino_min <- d_min[linhas_treino,]
d_teste_min <- d_min[-linhas_treino,]

d_mai <- carregar_treino('C:/Users/Athos/Downloads/treino/maiusculo/')
d_mai$letra <- as.factor(d_mai$letra)
d_treino_mai <- d_mai[linhas_treino,]
d_teste_mai <- d_mai[-linhas_treino,]

```

#### Tree
```{r}
modelo_tree <- tree(letra ~ ., data = select(d_treino, -arq))
cv_tree <- cv.tree(modelo_tree)
plot(cv_tree)
modelo_tree <- prune.tree(modelo_tree, best = 25)
save(d_treino, file = 'data/d_treino.rda')
save(modelo_tree, file = 'data/modelo.rda')
devtools::document(); devtools::install()
```

#### Random Forest
```{r}
library(doParallel)
cl <- makePSOCKcluster(2)
registerDoParallel(cl)

set.seed(19910401)
modelo_rf_min <- train(letra ~ ., 
                       data = select(d_treino_min, -arq),
                       method = "rf",
                       tuneLength = 2)

modelo_rf_mai <- train(letra ~ ., 
                       data = select(d_treino_mai, -arq),
                       method = "rf",
                       tuneLength = 2)

modelo_min <- modelo_rf_min$finalModel
modelo_mai <- modelo_rf_mai$finalModel

d <- ler(baixar())
teste <- carregar_teste(d)
nm <- names(select(d_treino, -arq, -letra))
teste[, nm[!nm %in% names(teste)]] <- 0

predicao <- predict(modelo_mai, d_teste_mai, type = "class")

r <- paste0(predicao, collapse = "")
r
desenhar(d)
```

### Prever!

```{r}
d <- ler("arq.png"); desenhar(d); prever(d)
```

